---
- hosts: windows
  any_errors_fatal: false
  tasks:
    - name: install nodejs 4
      win_chocolatey:
        name: nodejs.install
        version: 4.6.1
        params: --allow-downgrade
    - name: check nodejs install
      win_command: node -v
      register: nodev
    - debug: msg="Checked the installed version is {{ nodev.stdout }}."
    - assert:
        that:
          - "'4.6.1' in nodev.stdout"
