---
- name: install nodejs 6
  win_chocolatey:
    name: nodejs.install
    version: 6.9.4
    become: true
- name: Check nodejs install
  win_command: node -v
  register: nodev
  changed_when: false
- debug: msg="Checked the installed version is {{ nodev.stdout }}."
- assert:
    that:
      - "'6.9.4' in nodev.stdout"
