---
- name: Copy over Blackmagic Desktop Video Windows tools
  win_copy:
    dest: c:\Temp\Blackmagic_Desktop_Video_Windows_10.8.4.zip
    src: distros/bmd/Blackmagic_Desktop_Video_Windows_10.8.4.zip
- name: Unzip BMD tools
  win_unzip:
    src: c:\Temp\Blackmagic_Desktop_Video_Windows_10.8.4.zip
    dest: c:\Temp\bmd_tools
    creates: 'c:\\Temp\\bmd_tools\\Desktop Video Installer v10.8.4.msi'
- name: Install Blackmagic MSI
  win_package:
    path: 'c:\\Temp\\bmd_tools\\Desktop Video Installer v10.8.4.msi'
    product_id: '{6A663D66-4AAA-45AF-B7C1-7EB7BAF6FAE3}'
    state: present
    become: true
  register: result
- name: Reboot after BMD install
  win_reboot:
  when: result.changed
