---
- name: Copy over Blackmagic Desktop Video Windows tools
  win_copy:
    dest: "{{ ansible_user_dir }}\\Blackmagic_Desktop_Video_Windows_10.9.3.zip"
    src: distros/bmd/Blackmagic_Desktop_Video_Windows_10.9.3.zip
- name: Unzip BMD tools
  win_unzip:
    src: "{{ ansible_user_dir }}\\Blackmagic_Desktop_Video_Windows_10.9.3.zip"
    dest: "{{ ansible_user_dir }}\\bmd_tools"
    creates: "{{ ansible_user_dir }}\\bmd_tools\\Desktop Video Installer v10.9.3.msi"
- name: Install Blackmagic MSI
  win_package:
    path: "{{ ansible_user_dir }}\\bmd_tools\\Desktop Video Installer v10.9.3.msi"
    product_id: '{3A5C5F3F-83C5-4168-8645-12615D2DDB4D}'
    state: present
    become: true
    arguments: /norestart
  register: result
- name: Reboot after BMD install
  win_reboot:
  when: result.changed
